<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:10.
 */
class configuracaoAdminTest extends PHPUnit_Framework_TestCase {

    /**
     * @var configuracaoAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new configuracaoAdmin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers configuracaoAdmin::AfterLoad
     * @todo   Implement testAfterLoad().
     */
    public function testAfterLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configuracaoAdmin::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configuracaoAdmin::group
     * @todo   Implement testGroup().
     */
    public function testGroup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers configuracaoAdmin::configure
     * @todo   Implement testConfigure().
     */
    public function testConfigure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
