<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:08.
 */
class site_configuracaoModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var site_configuracaoModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new site_configuracaoModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers site_configuracaoModel::LoadFiles
     * @todo   Implement testLoadFiles().
     */
    public function testLoadFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_configuracaoModel::LoadFileValue
     * @todo   Implement testLoadFileValue().
     */
    public function testLoadFileValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_configuracaoModel::LoadFileForm
     * @todo   Implement testLoadFileForm().
     */
    public function testLoadFileForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_configuracaoModel::setDefaultConfig
     * @todo   Implement testSetDefaultConfig().
     */
    public function testSetDefaultConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_configuracaoModel::saveConfig
     * @todo   Implement testSaveConfig().
     */
    public function testSaveConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
