<?php

echo "<h2>{$grupo['name']}</h2><hr/>";

if(!empty($files)){
    $this->LoadResource('formulario', 'form');
    $this->LoadModel('site/configuracao', 'model');
    echo "<div class='config'>";
    foreach($files as $file){
        $this->form->printable();
        $url     = $this->Html->getLink("site/configuracao/configure/{$file['cod_cfile']}");
        //$editurl = $this->Html->getActionLinkIfHasPermission("site/conffile/edit/{$file['cod_cfile']}", "Editar Arquivo", "editarq");
        $resturl = $this->Html->getLink("site/configuracao/restore/{$file['cod_cfile']}");
        $dados   = $this->model->LoadFileForm($file['cod_cfile']);
        $values  = $this->model->LoadFileValue($file['cod_cfile']);
        //die();
        $html   = $this->form->NewForm($dados, $values, array(), true, $url);
        $id     = "form_{$file['cod_cfile']}";
        echo "
            <div class='subitem'> 
                <div class='title'>{$file['title']} </div>
                <div class='descricao'>{$file['descricao']}</div>
                <div class='formcontainer' id='$id' style='display:none;'>$html</div>
                <div class='acoes'><a href='#$id' class='loadconf'>Editar</a> - <a href='$resturl' class='restore'>Restaurar Padrão</a></div>
            </div>
        ";
    }
    echo "</div>";
}

?>

<script type="text/javascript">
    var classe = 'expandido';
    $('.loadconf').click(function(event){
        
        //previne o padrão do evento click
        event.preventDefault();
        
        //esconde os outros itens do menu
        var obj = $(this);
        $('.loadconf').each(function(){
            if($(this).attr('href') != obj.attr('href')){
                $(this).parent().parent().children('.formcontainer').slideUp('fast');
                $(this).html('Editar'); 
            }
        });
        
        //alterna a classe e o texto do link clicado
        $(this).parent().parent().children('.formcontainer').slideToggle('fast');
        if($(this).hasClass(classe)){$(this).html('Editar');}
        else{$(this).html('Fechar');}
        $(this).toggleClass(classe);
    });
    
    $('.restore').click(function(event){
        event.preventDefault();
        var url = $(this).attr('href');
        $.ajax({
            url: url,
            type: 'POST',
            dataType: 'json',
            success: function(json) {
                blockUI_unwait();
                if(typeof json.redirect != 'undefined') {
                    window.location.href = json.redirect;
                }
                if(json.status == 1){
                    if (typeof json.success != 'undefined' && json.success != '') blockUI_success(json.success);
                    else if(typeof json.alert != 'undefined' && json.alert != '') blockUI_alert(json.alert);
                    else blockUI_error('Operação concluída, mas sem resposta do servidor!');
                }else{
                    if (typeof json.erro != 'undefined') blockUI_error(json.erro);
                    else blockUI_error('Operação concluída, mas sem resposta do servidor!');
                }
            },
            error: function(erro){
                blockUI_unwait();
                blockUI_error("Erro na comunicação com o site");
            }
        });
    });
</script>

<style type="text/css">
    
    .subitem{
        margin-bottom: 18px;
    }

    .subitem > .title{
        font-size: 18px;
        margin-bottom: 3px;
    }
    
    .subitem > .descricao{
        font-size: 14px;
        margin-bottom: 6px;
    }
   
    
</style>