<?php

echo "<h2>{$grupo['name']}</h2><hr/>";

if(!empty($files)){
    $this->LoadResource('formulario', 'form');
    $this->LoadModel('site/configuracao', 'model');
    echo "<div class='config'>";
    foreach($files as $file){
        $this->form->printable();
        $url     = $this->Html->getLink("site/configuracao/configure/{$file['cod_cfile']}");
        //$editurl = $this->Html->getActionLinkIfHasPermission("site/conffile/edit/{$file['cod_cfile']}", "Editar Arquivo", "editarq");
        $resturl = $this->Html->getLink("site/configuracao/restore/{$file['cod_cfile']}");
        $dados   = $this->model->LoadFileForm($file['cod_cfile']);
        $values  = $this->model->LoadFileValue($file['cod_cfile']);
        //die();
        $html   = $this->form->NewForm($dados, $values, array(), true, $url);
        $id     = "form_{$file['cod_cfile']}";
        echo "
            <div class='subitem'> 
                <div class='title'>{$file['title']} </div>
                <div class='descricao'>{$file['descricao']}</div>
                <div class='formcontainer' id='$id' style='display:none;'>$html</div>
                <div class='acoes'><a href='#$id' class='loadconf'>Editar</a> - <a href='$resturl' class='restore'>Restaurar Padrão</a></div>
            </div>
        ";
    }
    echo "</div>";
}

$link = \classes\Classes\Registered::getPluginLocationUrl('site')."/js/grupo.js";
$this->Html->LoadJs($link);

?>

<style type="text/css">
    
    .subitem{
        margin-bottom: 18px;
    }

    .subitem > .title{
        font-size: 18px;
        margin-bottom: 3px;
    }
    
    .subitem > .descricao{
        font-size: 14px;
        margin-bottom: 6px;
    }
   
    
</style>