<style>
    .treeview ul{
        background-color: #e2e2e2!important;
    }
</style>

<div class='col-xs-3 border' id="divmenu">
    <h4><?php echo $title; ?></h4>
    <?php $this->LoadClassFromPlugin("site/index/indexFileManagerComponent", 'ifmc')->showMenu($files, $base_url);?>
</div>
<div class='logcontent col-xs-9 pull-right'>
    <?php if($filesrc !== ""){
     echo nl2br(file_get_contents($filesrc));
    }?>
</div>