<?php

$this->Html->LoadAngular('');
$this->Html->LoadAngular('angular-animate.min');
$this->Html->LoadAngular('ng-sanitize');

?>
<script type="text/javascript">
    
angular.module('tutorialApp', ['ngAnimate', 'ngSanitize']).controller('tutorialInicioCtrl',function($scope, $http, $window) {
    $scope.url   = window.location.host;
    $scope.step  = [];
    $scope.steps = {};
    $scope.depth = {};
    
    $scope.nextStep = function(target){
        if(typeof $scope.steps[target] === 'undefined'){return;}
        if(typeof $scope.steps[target]['redirect'] !== 'undefined'){
            $window.location = $scope.steps[target]['redirect'] ;
        }
        $scope.step  = $scope.steps[target];
        $scope.depth[target] = $scope.step;
    };
    var init = function(){
        var url = 'http://'+$scope.url+"/plugins/site/data.php";
        $http({method: 'GET', url: url}).success(function(data){
            $scope.steps = data;
            $scope.nextStep('mrgrana');
        });
    };
    init();
});;

</script>



<img src="<?php echo URL."/plugins/site/index/views/";?>mrgrana.png" class="pull-left"/>

<div ng-app="tutorialApp" ng-controller="tutorialInicioCtrl">
    <div class='col-xs-3 widget'>
        <div class="breadcrumb"><a href="" ng-repeat="d in depth" ng-click="nextStep(d.target)">{{d.title}}</a></div>
        <h4>{{step.title}}</h4>
        <div class='text' ng-bind-html='step.text'></div>
        <div class='options' ng-repeat="opt in step.options">
            <button class='btn pull-left' ng-class="opt.classe" ng-click="nextStep(opt.target)">{{opt.title}}</button>
        </div>
    </div>
</div>
