<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:20.
 */
class site_conffileModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var site_conffileModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new site_conffileModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers site_conffileModel::paginate
     * @todo   Implement testPaginate().
     */
    public function testPaginate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_conffileModel::checkSavePermission
     * @todo   Implement testCheckSavePermission().
     */
    public function testCheckSavePermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_conffileModel::getPermissionArr
     * @todo   Implement testGetPermissionArr().
     */
    public function testGetPermissionArr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_conffileModel::loadFormValues
     * @todo   Implement testLoadFormValues().
     */
    public function testLoadFormValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_conffileModel::unstall
     * @todo   Implement testUnstall().
     */
    public function testUnstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_conffileModel::updateFile
     * @todo   Implement testUpdateFile().
     */
    public function testUpdateFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
