<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:15.
 */
class site_confgrupoModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var site_confgrupoModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new site_confgrupoModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers site_confgrupoModel::genMenu
     * @todo   Implement testGenMenu().
     */
    public function testGenMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_confgrupoModel::getWebmasterGroups
     * @todo   Implement testGetWebmasterGroups().
     */
    public function testGetWebmasterGroups() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers site_confgrupoModel::findNewGroups
     * @todo   Implement testFindNewGroups().
     */
    public function testFindNewGroups() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
