<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:15.
 */
class confgrupoRegisterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var confgrupoRegister
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new confgrupoRegister;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers confgrupoRegister::insertConfgrupo
     * @todo   Implement testInsertConfgrupo().
     */
    public function testInsertConfgrupo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
